# -*- coding: utf-8 -*-
"""
Created on Fri Jun 24 20:43:24 2022

@author: omprakash majoju
"""

"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.

"""
def even_feb(x):
    a=0
    b=1
    count=0
    for i in range(0,x,2):
        c=a+b 
        a=b
        b=c
        if (c%2==0):
                count=count+c
        #print(c)
    print(count)
    a=b
    b=c
x=int(input("enter the range : ")) 
even_feb(x)

# 0 1 2 3 5 8 13 

"""
Sample output 1:
    enter the range : 50
    60696
    
Sample output 2:
    enter the range : 100
    26658145586
    
"""
